### ISSUE TITLE
Character Render

### ISSUE THREAD

**Issue by Lijun-Yu** [scs-master-deans-committee/scs-master-deans-committee.github.io#2]
At [this line](https://github.com/scs-master-deans-committee/scs-master-deans-committee.github.io/blob/9596e7271fe61d504ee873af86c658fb219ed3e3/data/minutes.js#L260), `they'll` is incorrectly rendered as `Theyâ€™ll`.

**Comment by Lijun-Yu** [comment]
I checked the screenshots @anant-kaushik provided on Slack and didn't see this problem, so this may be platform-specific.

Later I checked this only happens when I use Safari, while Chrome works just fine.

**Comment by anant-kaushik** [comment]
I couldn't reproduce it on Safari but will take a look again.

**Comment by Lijun-Yu** [comment]
Safari 13.1.2 (15609.3.5.1.3) on macOS Catalina 10.15.6

Another similar one is at the bottom left:
```raw
Copyright Â© 2020 - 2020
```
