### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Lijun-Yu** [scs-master-deans-committee/scs-master-deans-committee.github.io#3]
@anant-kaushik  For the minutes [file](https://github.com/scs-master-deans-committee/scs-master-deans-committee.github.io/blob/dev/data/minutes.js#L260) and potentially future data files, do we consider using the standard JSON format instead of `.js`? 

Providing a JSON schema according to the app implementation would also be great. But given it's under active development, this can be done later.

In general, these efforts would make it much easier for weekly updates and maintenance.

**Comment by anant-kaushik** [comment]
Importing json in html is not that simple. We need to a server running in the backend to supply the json. It is json just declared as a variable so that it could be imported to html as a js.
