### ISSUE TITLE
Release branch protection

### ISSUE THREAD

**Issue by anant-kaushik** [scs-master-deans-committee/scs-master-deans-committee.github.io#6]
The release branch contains the code of the website show to the public. It should be protected to allow only pull requests to make changes to that branch.

**Comment by Lijun-Yu** [comment]
Yeah, it should be protected. But one thing I'm not sure about is the difference between master and release. Suppose we are basically working on dev, using master as the "release" branch should be fine.

**Comment by anant-kaushik** [comment]
Master should be working development features that we want to showcase to the community. Dev can have broken features that need more eyes. The release is versioned production resources.

**Comment by Lijun-Yu** [comment]
Versioned releases can be managed via tags. But since GitHub pages need to be backed with a branch, let's use the release for this purpose.
It's now protected.

**Comment by anant-kaushik** [comment]
You are right I forgot about them, my bad

**Comment by anant-kaushik** [comment]
We can shift dev to master then. No problems.
